apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-deployment
  labels:
    app: maven-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: maven-deployment   
  template:
    metadata:
      labels:
        app: maven-deployment
    spec:
      containers:
      - name: maven
        image: sbhalsing0/maven:tag
        ports:
        - containerPort: 8080
      serviceAccountName: jenkins
---
apiVersion: v1
kind: Service
metadata:
  name: my-maven-svc
  labels:
    app: maven-deployment
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30007
    protocol: TCP
    name: http
