apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-deployment
  labels:
    app: maven
spec:
  replicas: 3
  selector:
    matchLabels:
      app: maven
  template:
    metadata:
      labels:
        app: maven
    spec:
      containers:
      - name: maven
        image: sbhalsing0/maven:tag
        ports:
        - containerPort: 8080
      serviceAccountName: jenkins
---
apiVersion: v1
kind: Service
metadata:
  name: my-maven
  labels:
    app: maven
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
